### ISSUE TITLE
[question] other custom types (helpers, etc..)

### ISSUE THREAD

**Issue by Coobaha** [mzgoddard/ember-loader#33]
Hi @mzgoddard!  I am trying to use your loader and got stuck with custom types.
Please, can you explain how to use them, for example handlebars helpers from app/helpers?
I should define type helper in webpack config?

It will be awesome to have some examples. Thanks!

**Comment by mzgoddard** [comment]
@Coobaha You could write handlebar helpers like initializers and add them to Ember.Handlebars in an initializer.

https://gist.github.com/mzgoddard/44548ee8dbae8cb90cad

Yeah definitely need to finish and write plenty more examples.

**Comment by Coobaha** [comment]
@mzgoddard :+1:
